# We have 3 type of variables which can be defined
#
# 1. step level     ( Only available for the particular step)
# 2. job level      ( will be available throughout the job)
# 3. workflow level (will be available throughout the workflow, i.e. global variables for the workflow)

# We can use the env in both ways

# 1. $Variable
# 2. ${{ env.Variable }}. <-- This is recomended

###################################################
name: Exploring variables and secrets
env:                                                            # This is on workflow level
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: arupdockerhub
  DOCKER_IMAGE: github-actions-nginx

on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest

      - name: Docker login
        env:
          DOCKER_PASSWORD: dockerpassw0rd                                                   # This is  called step level variable
        run: echo docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}

      - name: Docker publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the image in Docker
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          
