name: My first workflow
on: [ push, workflow_dispatch ]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v6

            - name:  List and read files
              run: |                    # we need to use this "|" for multi-line codes
                echo "My first GH actions job"
                ls -ltra
                cat README.md

            # - name: Listing the files
            #   run: ls
            # - name: Read README file
            #   run: cat README.md
